# qdrant

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data:/qdrant/storage
    restart: always
    networks:
      - ai_network

networks:
  ai_network:
    external: true
