# ollama on ai_network always

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-cpu
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/data:/root/.ollama
    environment:
      - MODEL=${OLLAMA_MODEL}
    restart: always
    networks:
      - ai_network

networks:
  ai_network:
    external: true
