# postgres docker-compose with dynamic init.sql

services:
  postgres:
    image: "postgres:17"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE}
    volumes:
      - "./data:/var/lib/postgresql/data"
      - "./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"  # Dynamic init script
    restart: always
    networks:
      - ai_network

networks:
  ai_network:
    external: true
